export const ERROR_CODES = {
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  EDITOR_UNAVAILABLE: "EDITOR_UNAVAILABLE",
  BRIDGE_PROTOCOL_ERROR: "BRIDGE_PROTOCOL_ERROR",
  REVISION_CONFLICT: "REVISION_CONFLICT",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNSAFE_OPERATION: "UNSAFE_OPERATION",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  PLAN_NOT_APPLIED: "PLAN_NOT_APPLIED",
  PLAN_ALREADY_APPLIED: "PLAN_ALREADY_APPLIED",
  PLAN_ALREADY_ROLLED_BACK: "PLAN_ALREADY_ROLLED_BACK",
  OPERATION_REJECTED: "OPERATION_REJECTED",
  ROLLBACK_FAILED: "ROLLBACK_FAILED",
  RUN_FAILED: "RUN_FAILED",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_INVALID_STATUS: "TASK_INVALID_STATUS",
  TASK_VERIFICATION_FAILED: "TASK_VERIFICATION_FAILED",
  PROJECT_BUSY: "PROJECT_BUSY",
  LEASE_NOT_FOUND: "LEASE_NOT_FOUND",
  LEASE_INVALID: "LEASE_INVALID",
  LEASE_EXPIRED: "LEASE_EXPIRED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class DomainError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = "DomainError";
  }
}
